version: "3.9"
services:
  fastapi:
    build: ./backend/fastapi
    ports:
      - "8000:8000"
    env_file:
      - ./backend/fastapi/.env

  nodejs:
    build: ./backend/nodejs
    ports:
      - "4000:4000"
